
package korisni;

import java.awt.BorderLayout;
import java.awt.Container;
import java.io.PrintStream;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/**
 * Materijali za predmet programski jezik JAVA
 * @author Amel Džanić
 */
public class konzola extends javax.swing.JInternalFrame {
    JTextArea textArea = new JTextArea (25, 80);
    /**
     * Creates new form konzola
     */
    public konzola() {
        initComponents();        
        Container contentPane = this.getContentPane();
        contentPane.setLayout (new BorderLayout ());
        contentPane.add (
            new JScrollPane (
                textArea, 
                JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, 
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED),
            BorderLayout.CENTER);
        JTextAreaOutputStream out = new JTextAreaOutputStream (textArea);
        //za povećanje fonta
        textArea.setFont(textArea.getFont().deriveFont(12f));
        System.setOut (new PrintStream (out));
    }
    
    
    public void clear (){
        textArea.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("KONZOLA");
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
