/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Korisnik;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author TFB5
 */
public class unosKorisnika extends javax.swing.JInternalFrame {
    /**
     * Varijabla mod određuje da li je unos ili ažuriranje
     * 0 - unos
     * 1- azuriranje
     */
    private int mod = 0;
    private korisnik selektovani = null;

    /**
     * Creates new form unosKorisnika
     */
    public unosKorisnika() {
        mod=0;
        initComponents();
        
    }

    /**
     *
     * @param k
     * @param mod
     */
    public unosKorisnika(korisnik k,int mod){
        this.mod=mod;
        selektovani=k;
        initComponents();
        jTextField2.setEnabled(false);
        
        if (mod==1){
            jButton1.setText("Ažuriraj");
            jTextField1.setText(k.getImeiprezime());
            jTextField2.setText(k.getUser());
            
            jPasswordField1.setEnabled(false);
            jPasswordField2.setEnabled(false);
        
        }
        if(mod==2){
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField1.setText(k.getImeiprezime());
            jTextField2.setText(k.getUser());
            jButton1.setText("Promjeni lozinku");            
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Unos novog korisnika");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Ime i prezime korisnika");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Korisničko ime");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Korisnička lozinka");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Ponovno lozinka");

        jButton1.setText("Unesi korisnika");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Vrsta korisnika");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPasswordField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pass = String.valueOf(jPasswordField1.getPassword());
        String potvrda = String.valueOf(jPasswordField2.getPassword());
        if(mod==0){
            System.out.println("Akcija za unos podataka");
            korisnik novi = new korisnik();
            korisnikKontroler kk = new korisnikKontroler();
            novi.setImeiprezime(jTextField1.getText());
            novi.setUser(jTextField2.getText());

            if(pass.equals(potvrda) && jTextField1.getText().length()>3 && jTextField2.getText().length()>3){
                novi.setPass(pass);
                try {
                    if (novi.getImeiprezime()==null) System.out.println("Greska");
                    kk.UnesiKorisnika(novi);
                    JOptionPane.showMessageDialog(rootPane, "Uspješan unos korisnika");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Greška sa SQL-om");
                    System.out.println("Exception:\n" + ex);
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Lozinke ne odgovaraju!!!"); 
            }
        }
        if(mod==1){
            selektovani.setImeiprezime(jTextField1.getText());
            selektovani.setUser(jTextField2.getText());
            korisnikKontroler kk = new korisnikKontroler();
            try {
                kk.azurirajKorisnika(selektovani);
                System.out.println(selektovani);
                JOptionPane.showMessageDialog(rootPane, "Uspješno ažuriranje korisnika");
                this.dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Greška sa SQL-om");
                System.out.println("Exception:\n" + ex);
            }
        }
        if(mod==2){
            if(pass.equals(potvrda)){
                korisnikKontroler kk = new korisnikKontroler();
                selektovani.setPass(pass);
                try {
                    kk.promjenaPassworda(selektovani, pass, pass);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Greška sa SQL-om");
                    System.out.println("Exception:\n" + ex);
                }
                
            }
            else {
              JOptionPane.showMessageDialog(rootPane, "Lozinke ne odgovaraju!!!");  
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
